name: Build Lens

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag or branch'
        required: true
        default: 'refs/heads/master'
        type: string
  push:
    tags: [ 'v**' ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: github.event_name != 'workflow_dispatch'

      - name: Checkout
        uses: actions/checkout@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ inputs.ref }}

      - name: Export version to variable
        shell: bash
        run: |
          export VERSION_STRING=$(cat packages/core/package.json | jq '.version' -r | xargs printf "%s")
          echo "VERSION_STRING=$VERSION_STRING" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install specific npm version
        run: npm install -g npm@^9.6.7

      - name: Build Lens
        env: 
          DOWNLOAD_ALL_ARCHITECTURES: true
        run: |
          mkdir releasefiles
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install visualstudio2019buildtools visualstudio2019-workload-vctools
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            ELECTRON_BUILDER_EXTRA_ARGS="--arm64 --x64 --config.mac.identity=null"
            sed -i '' "s/--publish onTag/& $ELECTRON_BUILDER_EXTRA_ARGS/" open-lens/package.json
          fi

          # fix x86 binaries in arm64 builds
          sed -i '' 's/\"npmRebuild\": false/\"npmRebuild\": true/g' open-lens/package.json
          
          npm run all:install

          # Avoid npm install from electron-builder
          mkdir -p open-lens/node_modules

          npx nx run open-lens:build:app
          
          ls -al open-lens/dist
          cp open-lens/dist/*.{dmg,zip,AppImage,deb,rpm,exe} releasefiles || :
        shell: bash

      - name: Calculate SHA256 checksum
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            certutil -hashfile OpenLens-${{ env.VERSION_STRING }}.exe SHA256 > OpenLens-${{ env.VERSION_STRING }}.exe.sha256
          else
            for filename in OpenLens-${{ env.VERSION_STRING }}*; do shasum -a 256 ${filename} > ${filename}.sha256 ; done
          fi
        shell: bash
        working-directory: releasefiles

      - name: Release
        uses: softprops/action-gh-release@v0.1.12
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: v${{ env.VERSION_STRING }}
          files: |
              releasefiles/*.dmg
              releasefiles/*.AppImage
              releasefiles/*.deb
              releasefiles/*.rpm
              releasefiles/*.zip
              releasefiles/*.exe
              releasefiles/*.sha256
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(inputs.ref, 'refs/tags/')
        with:
          body: https://github.com/lensapp/lens/releases/tag/v${{ env.VERSION_STRING }}
          name: v${{ env.VERSION_STRING }}
          tag_name: ${{ inputs.ref }}
          generate_release_notes: false
          files: |
              releasefiles/*.dmg
              releasefiles/*.AppImage
              releasefiles/*.deb
              releasefiles/*.rpm
              releasefiles/*.zip
              releasefiles/*.exe
              releasefiles/*.sha256
              
