name: Sync upstream

on:
  push:
    branches:
      - sync
  workflow_dispatch: 

jobs:
  sync-upstream:
    name: Sync upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          # requires `workflows` permission
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Reset extra commits
        run: |
          git reset --hard HEAD~2

      - name: Pull upstream changes
        run: |
          git remote add upstream https://github.com/lensapp/lens
          git fetch upstream master -t
          git rebase upstream/master

      - name: Remove upstream workflows
        run: |
          git config user.email "agologan@users.noreply.github.com"
          git config user.name "Alexandru Gologan"
          git rm -r .github/
          git commit -m 'Remove upstream workflows'

      - name: Add workflow changes
        run: |
          git cherry-pick origin/sync

      - name: Push changes
        run: |
          git push origin master --tags --force

      - name: Trigger build
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          set -x
          while read ver ; do
            gh workflow run build.yml -f ref=refs/tags/$ver -R $REPO
          done < <(comm -13 <(gh release list -R $REPO | cut -d$'\t' -f1 | sort) <(git tag --sort=-taggerdate | grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$" | head -n5 | sort))
